spring:
  # MySQL 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # local DB or Server DB (Container IP)
    url: jdbc:mysql://127.0.0.1:3306/capstone
    username: root
    password: 엄준식

  #jpa 설정
  jpa:
    hibernate:
      ddl-auto: update  # 또는 create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: maple
