name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Docker Image on GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image And Push Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/capstone-secret:tagname .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/capstone-secret:tagname

  deploy:
      runs-on: self-hosted
      needs: build

      steps:
        - name: Delete Old docker container
          run: docker rm -f back || true

        - name: Delete Old docker image
          run: docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/capstone-secret || true

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Pull Docker image
          run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/capstone-secret:tagname

        - name: Run Docker Container
          run:
            docker compose -f /home/ubuntu/docker-compose.yml up -d